application: metrotransitapi
version: 1
runtime: python
api_version: 1

handlers:
- url: /routes
  script: routes.py

- url: /direction
  script: direction.py

- url: /stops
  script: stops.py

- url: /nextrip
  script: nextrip.py

- url: .*
  script: main.py
